
--Q1
SELECT DISTINCT DIM_LOCATION.State
FROM            DIM_DATE INNER JOIN
                         FACT_TRANSACTIONS ON DIM_DATE.Date = FACT_TRANSACTIONS.Date INNER JOIN
                         DIM_LOCATION ON FACT_TRANSACTIONS.IdLocation = DIM_LOCATION.IdLocation
WHERE        (DIM_DATE.Year > 2005 AND DIM_DATE.Year < {fn NOW()})

--Q2
SELECT       TOP 1 DIM_LOCATION.State
FROM            FACT_TRANSACTIONS INNER JOIN
                         DIM_MODEL ON FACT_TRANSACTIONS.IdModel = DIM_MODEL.IdModel INNER JOIN
                         DIM_MANUFACTURER ON DIM_MODEL.IdManufacturer = DIM_MANUFACTURER.IdManufacturer INNER JOIN
                         DIM_LOCATION ON FACT_TRANSACTIONS.IdLocation = DIM_LOCATION.IdLocation
WHERE        (DIM_LOCATION.Country = 'US') AND (DIM_MANUFACTURER.Manufacturer_Name = 'Samsung')
GROUP BY DIM_LOCATION.State
ORDER BY SUM(FACT_TRANSACTIONS.TotalPrice) DESC

--Q3
SELECT        FACT_TRANSACTIONS.IdModel, DIM_LOCATION.ZipCode, DIM_LOCATION.State, COUNT(FACT_TRANSACTIONS.IdCustomer) AS [count of transactiosn]
FROM            FACT_TRANSACTIONS INNER JOIN
                         DIM_LOCATION ON FACT_TRANSACTIONS.IdLocation = DIM_LOCATION.IdLocation
GROUP BY FACT_TRANSACTIONS.IdModel, DIM_LOCATION.ZipCode, DIM_LOCATION.State

--Q4
SELECT TOP 1 DIM_MODEL.Model_Name
FROM   FACT_TRANSACTIONS INNER JOIN
       DIM_MODEL ON FACT_TRANSACTIONS.IdModel = DIM_MODEL.IdModel
GROUP BY DIM_MODEL.Model_Name
ORDER BY SUM(FACT_TRANSACTIONS.TotalPrice) ASC

--Q5
SELECT DIM_MANUFACTURER.Manufacturer_Name, FACT_TRANSACTIONS.IdModel, AVG(FACT_TRANSACTIONS.TotalPrice) AS [Average Price]
FROM   DIM_MANUFACTURER INNER JOIN
       DIM_MODEL ON DIM_MANUFACTURER.IdManufacturer = DIM_MODEL.IdManufacturer INNER JOIN
       FACT_TRANSACTIONS ON DIM_MODEL.IdModel = FACT_TRANSACTIONS.IdModel
WHERE DIM_MANUFACTURER.Manufacturer_Name IN (SELECT Manufacturer_Name FROM(SELECT DISTINCT TOP 5 DIM_MANUFACTURER.Manufacturer_Name, SUM(FACT_TRANSACTIONS.Quantity) AS [Total Quantity]
FROM   DIM_MANUFACTURER INNER JOIN
       DIM_MODEL ON DIM_MANUFACTURER.IdManufacturer = DIM_MODEL.IdManufacturer INNER JOIN
       FACT_TRANSACTIONS ON DIM_MODEL.IdModel = FACT_TRANSACTIONS.IdModel
GROUP BY DIM_MANUFACTURER.Manufacturer_Name
ORDER BY [Total Quantity]DESC)as a)
GROUP BY DIM_MANUFACTURER.Manufacturer_Name, FACT_TRANSACTIONS.IdModel
ORDER BY [Average Price]DESC;

--Q6
SELECT DIM_CUSTOMER.Customer_Name, AVG(FACT_TRANSACTIONS.TotalPrice) AS [Average_Price]
FROM   DIM_CUSTOMER INNER JOIN
       FACT_TRANSACTIONS ON DIM_CUSTOMER.IdCustomer = FACT_TRANSACTIONS.IdCustomer
GROUP BY DIM_CUSTOMER.Customer_Name, YEAR(FACT_TRANSACTIONS.Date)
HAVING YEAR(FACT_TRANSACTIONS.Date)=2009 AND (Average_Price)>500
ORDER BY [Average Price] DESC

--Q7
SELECT Model
From (SELECT TOP (5) DIM_MODEL.Model_Name as model
FROM  DIM_MODEL INNER JOIN
      FACT_TRANSACTIONS ON DIM_MODEL.IdModel = FACT_TRANSACTIONS.IdModel
GROUP BY DIM_MODEL.Model_Name, YEAR(FACT_TRANSACTIONS.Date)
HAVING (YEAR(FACT_TRANSACTIONS.Date) = '2008')
ORDER BY SUM(FACT_TRANSACTIONS.Quantity) DESC) as A
INTERSECT
SELECT Model
From (SELECT TOP (5) DIM_MODEL.Model_Name as model
FROM  DIM_MODEL INNER JOIN
      FACT_TRANSACTIONS ON DIM_MODEL.IdModel = FACT_TRANSACTIONS.IdModel
GROUP BY DIM_MODEL.Model_Name, YEAR(FACT_TRANSACTIONS.Date)
HAVING (YEAR(FACT_TRANSACTIONS.Date) = '2009')
ORDER BY SUM(FACT_TRANSACTIONS.Quantity) DESC) as B 
INTERSECT
SELECT Model
From (SELECT TOP (5) DIM_MODEL.Model_Name as model
FROM  DIM_MODEL INNER JOIN
      FACT_TRANSACTIONS ON DIM_MODEL.IdModel = FACT_TRANSACTIONS.IdModel
GROUP BY DIM_MODEL.Model_Name, YEAR(FACT_TRANSACTIONS.Date)
HAVING (YEAR(FACT_TRANSACTIONS.Date) = '2010')
ORDER BY SUM(FACT_TRANSACTIONS.Quantity) DESC) as C

--Q8
SELECT * FROM
(SELECT TOP 2 DIM_MANUFACTURER.Manufacturer_Name, SUM(FACT_TRANSACTIONS.TotalPrice) AS Sales,ROW_NUMBER()
FROM   FACT_TRANSACTIONS INNER JOIN
       DIM_MODEL ON FACT_TRANSACTIONS.IdModel = DIM_MODEL.IdModel INNER JOIN
       DIM_MANUFACTURER ON DIM_MODEL.IdManufacturer = DIM_MANUFACTURER.IdManufacturer
GROUP BY DIM_MANUFACTURER.Manufacturer_Name
HAVING YEAR(FACT_TRANSACTIONS.Date)=2009
ORDER BY Sales DESC
WHERE ROW_NUMBER()=2)
UNION ALL
(SELECT TOP 2 DIM_MANUFACTURER.Manufacturer_Name, SUM(FACT_TRANSACTIONS.TotalPrice) AS Sales,ROW_NUMBER()
FROM   FACT_TRANSACTIONS INNER JOIN
       DIM_MODEL ON FACT_TRANSACTIONS.IdModel = DIM_MODEL.IdModel INNER JOIN
       DIM_MANUFACTURER ON DIM_MODEL.IdManufacturer = DIM_MANUFACTURER.IdManufacturer
GROUP BY DIM_MANUFACTURER.Manufacturer_Name
HAVING YEAR(FACT_TRANSACTIONS.Date)=2010
ORDER BY Sales DESC
WHERE ROW_NUMBER()=2)

--Q9
SELECT DIM_MANUFACTURER.Manufacturer_Name
FROM FACT_TRANSACTIONS CROSS JOIN
     DIM_MANUFACTURER
WHERE (YEAR(FACT_TRANSACTIONS.Date) = 2009)
EXCEPT
SELECT DIM_MANUFACTURER.Manufacturer_Name
FROM   FACT_TRANSACTIONS CROSS JOIN
       DIM_MANUFACTURER
WHERE (YEAR(FACT_TRANSACTIONS.Date) = 2010)

--Q10
SELECT * 
From (SELECT TOP (100) DIM_CUSTOMER.Customer_Name,YEAR(FACT_TRANSACTIONS.Date) AS Year_, FACT_TRANSACTIONS.TotalPrice AS Average_Spend
FROM   FACT_TRANSACTIONS INNER JOIN
       DIM_CUSTOMER ON FACT_TRANSACTIONS.IdCustomer = DIM_CUSTOMER.IdCustomer
ORDER BY YEAR(FACT_TRANSACTIONS.Date), DIM_CUSTOMER.Customer_Name) AS a
PIVOT
(avg(Average_Spend) for Year_ in ([2005],[2006],[2007],[2008],[2009],[2010])) as ps


SELECT *
FROM (SELECT TOP (100) DIM_CUSTOMER.Customer_Name,YEAR(FACT_TRANSACTIONS.Date) AS Year_, (FACT_TRANSACTIONS.Quantity) AS Average_Quantity
FROM FACT_TRANSACTIONS INNER JOIN
     DIM_CUSTOMER ON FACT_TRANSACTIONS.IdCustomer = DIM_CUSTOMER.IdCustomer
ORDER BY YEAR(FACT_TRANSACTIONS.Date), DIM_CUSTOMER.Customer_Name) AS b
PIVOT
(avg(Average_Quantity) for Year_ in ([2005],[2006],[2007],[2008],[2009],[2010])) as pq